name: test and coverage

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-node@master
        with:
          node-version: 13

      - run: npm install
      - run: npx nodutilus-eslint
      - run: node test
      - run: npx nodutilus-nyc
